/**
 * EMP-Guardian - HAL implementation for STM32 (STM32Cube HAL library)
 * Author: Ciprian Ștefan Pleșca
 * License: MIT
 *
 * Reference target: STM32F411 (see docs/hardware_specs.md).
 *
 * BUILD NOTE: this file requires the STM32Cube HAL library and a
 * project-specific `main.h` / clock configuration generated by
 * STM32CubeMX (or written by hand) - it will not compile standalone
 * outside a real STM32Cube project. It has NOT been validated against
 * physical hardware - see MANIFESTO.md's epistemic-status section.
 * Pin assignments below are illustrative defaults; adjust to your PCB.
 *
 * Expected peripheral setup (done via CubeMX or manual init, not shown
 * here since it's project/board-specific):
 *   - ADC1, channel connected to the signal-conditioning circuit output
 *   - GPIOB pin 0, output push-pull, for the shield actuator
 *   - USART2 for telemetry
 */

#include "hal.h"
#include "stm32f4xx_hal.h"

extern ADC_HandleTypeDef hadc1;     /* generated by CubeMX */
extern UART_HandleTypeDef huart2;   /* generated by CubeMX */

#define SHIELD_ACTUATOR_GPIO_PORT   GPIOB
#define SHIELD_ACTUATOR_GPIO_PIN    GPIO_PIN_0

void emp_hal_board_init(void) {
    /* Clock tree, GPIO, ADC and UART peripheral init are generated by
     * CubeMX into SystemClock_Config()/MX_ADC1_Init()/MX_USART2_UART_Init()
     * in a real project - call them here, e.g.:
     *
     *   HAL_Init();
     *   SystemClock_Config();
     *   MX_GPIO_Init();
     *   MX_ADC1_Init();
     *   MX_USART2_UART_Init();
     */
}

uint16_t emp_detector_hal_read_adc(void) {
    uint16_t value = 0;
    HAL_ADC_Start(&hadc1);
    if (HAL_ADC_PollForConversion(&hadc1, 1) == HAL_OK) {
        value = (uint16_t)HAL_ADC_GetValue(&hadc1);
    }
    HAL_ADC_Stop(&hadc1);
    return value;
}

void emp_hal_gpio_write(int pin, bool level) {
    (void)pin; /* single actuator pin in this reference design */
    HAL_GPIO_WritePin(SHIELD_ACTUATOR_GPIO_PORT, SHIELD_ACTUATOR_GPIO_PIN,
                       level ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

void emp_hal_delay_ms(uint32_t ms) {
    HAL_Delay(ms);
}

void emp_hal_uart_init(uint32_t baudrate) {
    /* In a typical CubeMX project, USART2 is already configured with
     * its baud rate at generation time (huart2.Init.BaudRate). If you
     * need to change it at runtime, re-init here, e.g.:
     *
     *   huart2.Init.BaudRate = baudrate;
     *   HAL_UART_Init(&huart2);
     */
    (void)baudrate;
}

void emp_hal_uart_write(const char *data, int len) {
    HAL_UART_Transmit(&huart2, (uint8_t *)data, (uint16_t)len, HAL_MAX_DELAY);
}
